spring.application.name=sbapp02


server.port=2003


#DB Configuration

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/batch645
spring.datasource.username=root
spring.datasource.password=root


#JPA Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true